#!/bin/bash


#CONF_LIST=`find . -maxdepth 1 -not -name "install" -not -name ".*" -printf "%f\n"`

# works with osx bsd find
CONF_LIST=`find . -maxdepth 1 -not -name "install" -not -name ".*" -print0 | xargs -0 basename`

for CONF in $CONF_LIST; do
    SRC="$PWD/$CONF"
    DEST="$HOME/.$CONF"
    if [ ! -e $DEST ]; then
        ln -sv $SRC $DEST
    fi
done
