#!/bin/bash


PLATFORM=`uname`

if [[ "$PLATFORM" == "Linux" ]]; then
    CONF_LIST=`find . -maxdepth 1 -not -name "install" -not -name ".*" -printf "%f\n"`
elif [[ "$PLATFORM" == "Darwin" ]]; then
    # works with osx bsd find
    CONF_LIST=`find . -maxdepth 1 -not -name "install" -not -name ".*" -print0 | xargs -0 basename`
fi


for CONF in $CONF_LIST; do
    SRC="$PWD/$CONF"
    DEST="$HOME/.$CONF"
    if [ ! -e $DEST ]; then
        ln -sv $SRC $DEST
    fi
done
